name: aletheia_core_model
description: Aletheia Core Model
version: 0.0.29
homepage: https://www.biblealetheia.com
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.4.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  # test: ^1.24.0
