name: aletheia_core
description: Aletheia Core
version: 0.0.36

homepage: https://www.biblealetheia.com
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^5.0.0
  # test: ^1.24.0
