// ignore_for_file: constant_identifier_names

///Enum for WordDependencyEdge [Label]
enum TypeWordDependencyEdgeLabel {
  UNKNOWN('Unknown'),
  ABBREV('Abbreviation modifier'),
  ACOMP('Adjectival complement'),
  ADVCL('Adverbial clause modifier'),
  ADVMOD('Adverbial modifier'),
  AMOD('Adjectival modifier of an NP'),
  APPOS('Appositional modifier of an NP'),
  ATTR('Attribute dependent of a copular verb'),
  AUX('Auxiliary (non-main) verb'),
  AUXPASS('Passive auxiliary'),
  CC('Coordinating conjunction'),
  CCOMP('Clausal complement of a verb or adjective'),
  CONJ('Conjunct'),
  CSUBJ('Clausal subject'),
  CSUBJPASS('Clausal passive subject'),
  DEP('Dependency (unable to determine)'),
  DET('Determiner'),
  DISCOURSE('Discourse'),
  DOBJ('Direct object'),
  EXPL('Expletive'),
  GOESWITH('Goes with (part of a word in a text not well edited)'),
  IOBJ('Indirect object'),
  MARK('Marker (word introducing a subordinate clause)'),
  MWE('Multi-word expression'),
  MWV('Multi-word verbal expression'),
  NEG('Negation modifier'),
  NN('Noun compound modifier'),
  NPADVMOD('Noun phrase used as an adverbial modifier'),
  NSUBJ('Nominal subject'),
  NSUBJPASS('Passive nominal subject'),
  NUM('Numeric modifier of a noun'),
  NUMBER('Element of compound number'),
  P('Punctuatio("mark"),'),
  PARATAXIS('Parataxis relation'),
  PARTMOD('Participial modifier'),
  PCOMP('The complement of a preposition is a clause'),
  POBJ('Object of a preposition'),
  POSS('Possession modifier'),
  POSTNEG('Postverbal negative particle'),
  PRECOMP('Predicate complement'),
  PRECONJ('Preconjunt'),
  PREDET('Predeterminer'),
  PREF('Prefix'),
  PREP('Prepositional modifier'),
  PRONL('The relationship between a verb and verbal morpheme'),
  PRT('Particle'),
  PS('Associative or possessive marker'),
  QUANTMOD('Quantifier phrase modifier'),
  RCMOD('Relative clause modifier'),
  RCMODREL('Complementizer in relative clause'),
  RDROP('Ellipsis without a preceding predicate'),
  REF('Referent'),
  REMNANT('Remnant'),
  REPARANDUM('Reparandum'),
  ROOT('Root'),
  SNUM('Suffix specifying a unit of number'),
  SUFF('Suffix'),
  TMOD('Temporal modifier'),
  TOPIC('Topic marker'),
  VMOD('Clause headed by an infinite form of the verb that modifies noun'),
  VOCATIVE('Vocative'),
  XCOMP('Open clausal complement'),
  SUFFIX('Name suffix'),
  TITLE('Name title'),
  ADVPHMOD('Adverbial phrase modifier'),
  AUXCAUS('Causative auxiliary'),
  AUXVV('Helper auxiliary'),
  DTMOD('Rentaishi (Prenominal modifier)'),
  FOREIGN('Foreign words'),
  KW('Keyword'),
  LIST('List for chains of comparable items'),
  NOMC('Nominalized clause'),
  NOMCSUBJ('Nominalized clausal subject'),
  NOMCSUBJPASS('Nominalized clausal passive'),
  NUMC('Compound of numeric modifier'),
  COP('Copula'),
  DISLOCATED('Dislocated relation (for fronted/topicalized elements)'),
  ASP('Aspect marker'),
  GMOD('Genitive modifier'),
  GOBJ('Genitive object'),
  INFMOD('Infinitival modifier'),
  MES('Measure'),
  NCOMP('Nominal complement of a noun;');

  const TypeWordDependencyEdgeLabel(this._description);
  final String _description;

  String get description => _description;
}
